// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZZzY5qipPHRi9sSHXJo7hD__EPT4myJU',
    appId: '1:505635070098:web:091d66849478f8c9f8464b',
    messagingSenderId: '505635070098',
    projectId: 'dashgrocer-9f448',
    authDomain: 'dashgrocer-9f448.firebaseapp.com',
    storageBucket: 'dashgrocer-9f448.firebasestorage.app',
    measurementId: 'G-SL41W5HW5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQyKYg0gEQN05CfRl1KULh2joZ2PIx6rY',
    appId: '1:505635070098:android:92632d08e4a7c0d4f8464b',
    messagingSenderId: '505635070098',
    projectId: 'dashgrocer-9f448',
    storageBucket: 'dashgrocer-9f448.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrVcSYGB7BC1R9UqFE3aKy_qqVxvVoU_M',
    appId: '1:505635070098:ios:477178b09ca4b48bf8464b',
    messagingSenderId: '505635070098',
    projectId: 'dashgrocer-9f448',
    storageBucket: 'dashgrocer-9f448.firebasestorage.app',
    iosBundleId: 'com.example.dashgrocer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrVcSYGB7BC1R9UqFE3aKy_qqVxvVoU_M',
    appId: '1:505635070098:ios:477178b09ca4b48bf8464b',
    messagingSenderId: '505635070098',
    projectId: 'dashgrocer-9f448',
    storageBucket: 'dashgrocer-9f448.firebasestorage.app',
    iosBundleId: 'com.example.dashgrocer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZZzY5qipPHRi9sSHXJo7hD__EPT4myJU',
    appId: '1:505635070098:web:3bfd3619dd8fc57df8464b',
    messagingSenderId: '505635070098',
    projectId: 'dashgrocer-9f448',
    authDomain: 'dashgrocer-9f448.firebaseapp.com',
    storageBucket: 'dashgrocer-9f448.firebasestorage.app',
    measurementId: 'G-7VKNHL5K4B',
  );
}
